version: "3"
services:
  nodebackend:
    build : ./node-backend
    ports:
      - "3000:3000"   
  portainer : 
    image : portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports : 
      - "9001:9000"

volumes : 
  portainer_data:

